// episodes-data.js — metadata for the DJ mix archive on the episodes page
// Track entries use plain objects {title, note, time} — rendering is the component's job

const STATIONS = [
  {
    freq: 88.9,
    epNum: "01",
    genre: "JUNGLE",
    title: "EP 01 – JUNGLE: ORIGINAL NUTTAH SHOCKWAVE",
    subtitle: "THE ROOTS OF THE BREAKBEAT",
    desc: "Enter the era when London’s illegal warehouse raves mutated into a darker, breakneck sound born from the concrete. This opening chapter traces jungle’s explosive rise from 1991–1993, where chopped breaks met deep sub-bass and Caribbean sound system culture. Lock your frequency and stay tuned to the underground pulse.",
    duration1: "52:14",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ CHARING CROSS, LONDON",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    colors: {
      neonGreen: "#39FF14",
      neonPink: "#FF2DAA",
      surfaceLowest: "#0e0d0a",
      surfaceLow: "#1c1b18"
    },
    vinylImg: "https://images.unsplash.com/photo-1539625319135-882b8340c1d6?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Jungle Magazine.png",
    cardDate: "11.10.25",
    cardEp: "EP 01 / SYSTEM",
    tracks1: [
      { title: "Lennie De Ice – We Are I.E. (1991)", note: "The ultimate sonic bridge; unites bleep techno with heavy sub-bass and accelerated breakbeats.", time: "00:00" },
      { title: "SL2 – On A Ragga Tip (1992)", note: "Collides UK rave with Jamaican sound system culture, establishing the foundational ragga jungle blueprint.", time: "04:15" },
      { title: "Rufige Kru – Terminator (1992)", note: "Pioneers time-stretching on drum breaks to birth the metallic, moody darkcore aesthetic.", time: "08:30" },
      { title: "Origin Unknown – Valley of the Shadows (1993)", note: "Perfects atmospheric early jungle, balancing a legendary vocal sample with sweeping, sci-fi production.", time: "12:45" },
      { title: "Omni Trio – Renegade Snares (Foul Play Remix) (1993)", note: "Elevates the breakbeat from a rhythmic backing track into a complex, chopped lead instrument.", time: "17:10" },
      { title: "DJ Crystl – Warpdrive (1993)", note: "Captures the futuristic, intelligent pirate radio energy just before the underground exploded.", time: "21:40" },
      { title: "UK Apachi with Shy FX – Original Nuttah (1994)", note: "The ultimate crossover anthem; exports raw ragga jungle from the underground into the national charts.", time: "26:05" },
      { title: "M-Beat feat. General Levy – Incredible (1994)", note: "The commercial peak of ragga jungle that triggered an underground backlash and a deeper sonic shift.", time: "30:20" },
      { title: "Goldie – Inner City Life (1994)", note: "A lush, emotional masterpiece proving the genre belonged on full-length LPs, not just dancefloor 12-inches.", time: "34:35" },
      { title: "Roni Size – Music Box (1995)", note: "Unveils the rolling Bristol sound, driving sophisticated jazz double-bass licks to the forefront.", time: "39:00" },
      { title: "Alex Reece – Pulp Fiction (1995)", note: "Strips away chaotic breakbeats for a clean, driving two-step rhythm, piloting modern drum and bass.", time: "43:30" },
      { title: "DJ Trace – Mutant Revisited (1995)", note: "Birth of tech-step; deploys cold, dystopian Reese basslines to signal a dark new era.", time: "47:50" }
    ]
  },
  {
    freq: 91.2,
    epNum: "02",
    genre: "DRUM & BASS",
    title: "EP 02 – DRUM & BASS: SYMPHONIES IN THE SUB",
    subtitle: "THE ART OF THE ROLLING BREAKBEAT",
    desc: "Witness the rave retreat underground as late-90s jungle mutates into the sleek machine pressure of drum & bass. Relentless two-step rhythms and snarling tech-step basslines redefine the sound of the city. Hold the frequency and stay locked to the heartbeat of the streets.",
    duration1: "59:08",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ HOXTON",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    colors: {
      neonPink: "#0066FF",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0f0a0a",
      surfaceLow: "#1d1919"
    },
    vinylImg: "https://images.unsplash.com/photo-1542208998-f6dbbb27a72f?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Drum n Bass Magazine.png",
    cardDate: "28.11.25",
    cardEp: "EP 02 / MOTION",
    tracks1: [
      { title: "Adam F – Circles (1997)", note: "Fuses atmospheric jungle roots with precise D&B engineering using a rolling jazz sample.", time: "00:00" },
      { title: "Roni Size / Reprazent – Brown Paper Bag (1997)", note: "Brings live acoustic instrumentation to D&B, securing a historic Mercury Prize for the scene.", time: "03:15" },
      { title: "Ed Rush, Optical & Fierce – Alien Girl (1998)", note: "The definitive neurofunk blueprint; introduces heavy, mechanical, undulating Reese basslines.", time: "06:40" },
      { title: "Bad Company UK – The Nine (1998)", note: "Stripped of all melody; stands as the absolute pinnacle of underground groove and dancefloor engineering.", time: "10:10" },
      { title: "Dillinja – Hard Noize (1998)", note: "Peak tear-out sound; saturated sub-bass engineered to push heavy club hardware to its breaking point.", time: "13:30" },
      { title: "Micky Finn & Aphrodite – Bad Ass (1996)", note: "Laid the rowdy blueprint for early jump-up with bouncy beats and massive hip-hop sampling.", time: "16:50" },
      { title: "Shy FX & T Power – Shake Ur Body (2001)", note: "Defies brooding underground rules to score an inescapable daytime radio and pop chart hit.", time: "20:00" },
      { title: "High Contrast – Racing Green (2004)", note: "The quintessential liquid anthem; fires up lush soul and disco influences at a rolling 170 BPM.", time: "23:20" },
      { title: "Pendulum – Tarantula (2005)", note: "Deploys massive rock-band energy and synth leads to rip D&B out of clubs onto global festival stages.", time: "26:45" },
      { title: "DJ Hazard & D Minds – Mr Happy (2007)", note: "An inescapable jump-up phenomenon; its screeching, modulating bassline completely dominated the clubs.", time: "30:10" },
      { title: "Chase & Status – No Problem (2011)", note: "Blends hyper-aggressive modern production with tribal and reggae energy for stadium-level dominance.", time: "33:30" },
      { title: "DJ Zinc – 138 Trek (1999)", note: "A chronological pivot; drops the tempo to 138 BPM and accidentally bridges D&B to early garage.", time: "36:50" },
      { title: "Noisia & The Upbeats – Dead Limit (2015)", note: "The peak of modern electronic sound design, pushing neurofunk to hyper-detailed extremes.", time: "40:15" },
      { title: "Dimension & Sub Focus – Desire (2018)", note: "A stadium-sized masterclass in cinematic, emotional festival D&B for the global stage.", time: "43:40" },
      { title: "Hedex – MHITR (Semi-Automatic) (2023)", note: "Violently catchy modern jump-up designed for the social media age and a new generation of ravers.", time: "47:00" },
      { title: "Nia Archives – Baianá (2022)", note: "Ignites the modern DIY jungle revival, pairing live vocals with raw, classic chopped breaks.", time: "50:15" },
      { title: "venbee, goddard. – messy in heaven (2022)", note: "Pairs personal singer-songwriter vocals with heavy liquid rollers to conquer the UK Top 40.", time: "53:30" },
      { title: "Chase & Status feat. Bou – Baddadan (2023)", note: "A heavy, definitive decade-defining roller bridging sound system roots with hyper-modern production.", time: "56:20" }
    ]
  },
  {
    freq: 93.5,
    epNum: "03",
    genre: "UK GARAGE",
    title: "EP 03 – UK GARAGE & 2-STEP: THE CHAMPAGNE SHUFFLE",
    subtitle: "2 STEP & NIGHT BUS ANTHEMS",
    desc: "Step into the late-90s Sunday club scene where UK Garage brought soul, swagger, and designer style to the underground. At 130 BPM, producers fused house, sub-bass, and chopped vocals into the unmistakable swing of 2-step. Tune the system and stay locked to this syncopated lineage.",
    duration1: "58:45",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ SOHO",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    colors: {
      neonPink: "#D4AF37",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0e0e0e",
      surfaceLow: "#1c1b1b"
    },
    vinylImg: "https://lh3.googleusercontent.com/aida-public/AB6AXuB_wEXSaYe5BZlrbBz85FsiQPhXYuNmtsceeT8911HmmvBcYb70OvO05QR6z0iBcVhFC6BkaeY2rkmdWMmtTiP4_60J5CEXvMFVrO7gTG5ElV40pvpCdtt_gDmDP4XJVZHxNlLfB2ybldd71gezzBsalGNrMCebFuNSHxa3bAb7zzqBKPJHhtFLQPRys7jCtHasO0X8SDn0yStshoHpgrUatItDnucGtsFMBk44IN_eo9QVEXRlITTyCRXFvREzsoIfs7OgEhHu5qQ",
    cardImg: "images/Garage Magazine.png",
    cardDate: "04.12.25",
    cardEp: "EP 03 / SOUTH",
    tracks1: [
      { title: "Roy Davis Jr. ft. Peven Everett – Gabriel (Live Garage Mix) (1996)", note: "The foundational US-born blueprint that gave the UK scene a soulful escape from frantic breakbeats.", time: "00:00" },
      { title: "Tina Moore – Never Gonna Let You Go (Kelly G Bump-N-Go Dub) (1997)", note: "Syncopated vocal remix style that defined and maximized dancefloor swing for glamorous Sunday club nights.", time: "03:40" },
      { title: "Todd Edwards – Saved My Life (1995)", note: "Micro-chops vocals into rhythmic, percussive melodies, creating the absolute signature UKG production style.", time: "07:15" },
      { title: "Double 99 – Ripgroove (1997)", note: "The heavy speed garage template; weaponizes a 4x4 house beat with time-stretched vocal samples and jungle sub-bass.", time: "10:50" },
      { title: "Tuff Jam – Need Good Love (1997)", note: "The quintessential 4x4 champagne-era sound, packed with infectious swing and aspirational Sunday club energy.", time: "14:20" },
      { title: "MJ Cole – Sincere (1998)", note: "A broken, syncopated masterclass that removed the standard second and fourth kick drums to birth 2-step.", time: "18:00" },
      { title: "Shanks & Bigfoot – Sweet Like Chocolate (1999)", note: "Broke out of the underground to hit number one, cementing garage as a daytime radio pop phenomenon.", time: "21:45" },
      { title: "Sweet Female Attitude – Flowers (Sunship Mix) (2000)", note: "The definitive emotional peak, demonstrating that garage could carry deep, heartfelt soulful expression.", time: "25:10" },
      { title: "Artful Dodger – Re-Rewind (1999)", note: "A massive transatlantic anthem that shifted garage from underground to national pop phenomenon.", time: "28:50" },
      { title: "DJ Luck & MC Neat – A Little Bit of Luck (1999)", note: "The perfect MC-led anthem; establishes the classic DJ-MC pairing that defined the next decade of UK club music.", time: "32:30" },
      { title: "Wookie – Battle (2000)", note: "An irresistible fusion of deep house spirituality and UK garage syncopation, totally unique in its class.", time: "36:10" },
      { title: "Private / Zed Bias – Neighbourhood (2000)", note: "A moodier, deeper sound that signals the underground’s natural evolution and the beginning of proto-grime.", time: "39:50" },
      { title: "Sticky ft. Ms. Dynamite – Booo! (2001)", note: "A feminist declaration and street landmark; Ms. Dynamite’s raw lyricism reshapes the MC’s cultural role.", time: "43:30" },
      { title: "Oxide & Neutrino – Bound 4 Da Reload (Casualty) (2000)", note: "Completely stripped-back production; this is the raw pirate radio anthem that bridges garage directly into grime.", time: "47:10" },
      { title: "So Solid Crew – 21 Seconds (2001)", note: "A generation-defining chart-topper; gives 21 solo voices 21 seconds each, the purest distillation of collective power.", time: "50:50" },
      { title: "Pay As U Go Cartel – Champagne Dance (2001)", note: "An essential crew anthem bridging the gap between garage’s champagne-era glamour and the raw energy of nascent grime.", time: "54:30" }
    ]
  },
  {
    freq: 95.8,
    epNum: "04",
    genre: "GRIME",
    title: "EP 04 – GRIME: ESKIMO ICE AGE",
    subtitle: "8-BAR BEATS & RAW STREET POETRY",
    desc: "Enter East London in 2002 as a new generation builds a colder, harder sound from the concrete up. Garage is stripped back into icy synths, sharp 8-bar rhythms, and pirate radio clashes. Lock in the dial and stay tuned to the raw underground pulse.",
    duration1: "65:30",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ BOW E3",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    colors: {
      neonPink: "#B0B7C3",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0d0d0c",
      surfaceLow: "#1c1c1a"
    },
    vinylImg: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Grime magazine.png",
    cardDate: "28.11.25",
    cardEp: "EP 04 / SKYLINE",
    tracks1: [
      { title: "Wiley – Eskimo (2002)", note: "The blueprint. Icy synths, stuttering rhythms and minimalist production define grime’s foundational sound.", time: "00:00" },
      { title: "Wiley – Igloo (2003)", note: "Perfects the Eskimo Beat sound; an Arctic digital landscape that launched an entire scene.", time: "03:00" },
      { title: "Musical Mob – Pulse X (2002)", note: "The undetonated original; considered the first true grime instrumental recorded.", time: "06:10" },
      { title: "Dizzee Rascal – I Luv U (2003)", note: "Rascal’s ferocious, complex debut; sets a whole new bar for lyrical complexity and aggression in UK music.", time: "09:20" },
      { title: "Roll Deep – Terrible (2003)", note: "The defining collective anthem; showcases Roll Deep’s staggering lyrical depth and crew unity.", time: "12:30" },
      { title: "Lethal Bizzle – Pow (Forward) (2004)", note: "A violent, anarchic club phenomenon; its uncontrollable energy got it banned from multiple venues.", time: "15:40" },
      { title: "Kano – P’s & Q’s (2004)", note: "Kano’s definitive arrival; connects raw street poetry with elevated artistry and mainstream potential.", time: "18:50" },
      { title: "Ruff Sqwad – Functions on the Low (2004)", note: "A deeply melancholic yet hard-edged classic; cinematic emotionalism meets raw grime production.", time: "22:00" },
      { title: "Jme – Serious (2006)", note: "The Boy Better Know aesthetic crystallised; uncompromising, dry, and sharply self-aware.", time: "25:10" },
      { title: "Tempa T – Next Hype (2009)", note: "Pure, unfiltered aggression as an art form; became one of the genre’s greatest viral anthems.", time: "28:20" },
      { title: "Meridian Dan – German Whip (2014)", note: "The unexpected resurrection; a stripped-back, deadpan banger that reignited the mainstream’s interest in grime.", time: "31:30" },
      { title: "Skepta ft. Jme – That’s Not Me (2014)", note: "The manifesto of a generation refusing to compromise; the catalyst for grime’s global renaissance.", time: "34:40" },
      { title: "Stormzy – Shut Up (2015)", note: "Pure disdain as a masterpiece; became a UK chart phenomenon through an unstoppable internet campaign.", time: "37:50" },
      { title: "Skepta – Shutdown (2015)", note: "The ultimate peak of Boy Better Know’s movement; a genre-defining, generation-rallying anthem.", time: "41:00" },
      { title: "Kano – 3 Wheel-ups (2016)", note: "Effortlessly bridges street credibility and sophisticated artistry; the most celebrated MC/actor of his generation.", time: "44:10" },
      { title: "Stormzy – Big For Your Boots (2017)", note: "Commanding mainstream dominance while staying firmly rooted in grime’s confrontational values.", time: "47:20" },
      { title: "Dave & AJ Tracey – Thiago Silva (2016)", note: "A future grime legend is born; an effortlessly detailed lyrical showcase demanding a major record deal.", time: "50:30" },
      { title: "Ghetts ft. Skepta – IC3 (2020)", note: "A landmark collaboration; two legends at their absolute peak delivering one of grime’s finest moments.", time: "53:40" },
      { title: "D Double E ft. Kano – Tell Me A Ting (2019)", note: "Veteran excellence personified; a masterclass in controlled aggression and earned authority.", time: "56:50" },
      { title: "Kano ft. D Double E & Ghetts – Class of Deja (2019)", note: "A reunion of unparalleled significance; the three founding MCs reunite on Kano’s critically acclaimed HBO show.", time: "60:00" },
      { title: "Manga Saint Hilare – That’s How We Like It (2020)", note: "Underground authenticity preserved; Manga rejects all commercial compromise to deliver relentless, complex bars.", time: "63:10" }
    ]
  },
  {
    freq: 98.1,
    epNum: "05",
    genre: "DUBSTEP",
    title: "EP 05 – DUBSTEP: SOUTH OF THE RIVER SHADOWS",
    subtitle: "SUB-LOW FREQUENCIES & HALF-TIME BEATS",
    desc: "Travel to early-2000s Croydon where a quiet revolution reshaped underground bass music forever. Sparse rhythms and deep half-step basslines create a dark, meditative sound built to shake the floorboards. Dial in and keep the system locked to the deep underground.",
    duration1: "48:32",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ CROYDON",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    colors: {
      neonPink: "#2b21de",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0a0d0e",
      surfaceLow: "#181a1c"
    },
    vinylImg: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Dubstep Magazine .png",
    cardDate: "15.12.25",
    cardEp: "EP 05 / SUB LOW",
    tracks1: [
      { title: "El-B – Buck & Bury (2001)", note: "The proto-dubstep prototype; combines broken garage rhythms with an impossibly deep, rattling sub-bass.", time: "00:00" },
      { title: "Benga & Skream – The Judgement (2003)", note: "An early Rinse FM pirate radio recording that captures the nascent south London scene at its most raw.", time: "03:45" },
      { title: "Digital Mystikz – Haunted (2005)", note: "Pure atmospheric dread; DMZ’s defining sound of dark, spacious, meditative sub-bass pressure.", time: "07:30" },
      { title: "Loefah – Mud (2006)", note: "Industrial grade weight; Loefah’s bass hits like concrete, defining the most brutal end of the DMZ sound.", time: "11:15" },
      { title: "Skream – Midnight Request Line (2005)", note: "A transcendent dubstep classic; melodic enough for the charts, dark enough for the underground.", time: "15:00" },
      { title: "Burial – Archangel (2007)", note: "A genre-defining masterpiece; street-level melancholy and urban solitude given perfect musical form.", time: "18:45" },
      { title: "Benga & Coki – Night (2008)", note: "The explosive transition moment; bridges underground DMZ experimentalism with high-energy rave culture.", time: "22:30" },
      { title: "Rusko – Cockney Thug (2007)", note: "Where dubstep goes brostep; aggressive wobble bass designed for maximum dancefloor carnage.", time: "26:15" },
      { title: "Magnetic Man – I Need Air (2010)", note: "The mainstream summit; three dubstep titans combine to deliver a chart-friendly, emotionally resonant anthem.", time: "30:00" },
      { title: "La Roux – In For The Kill (Skream Remix) (2009)", note: "The crossover that changed everything; makes dubstep's wobble bass a global pop production tool.", time: "33:45" },
      { title: "Katy B – Katy On A Mission (2010)", note: "A defining cultural moment; the perfect marriage of garage-rave energy and modern dubstep production.", time: "37:30" },
      { title: "Joy Orbison – Hyph Mngo (2009)", note: "A beautiful, melancholic anomaly; brings genuine emotional depth and restraint back to the bass underground.", time: "41:15" },
      { title: "James Blake – CMYK (2010)", note: "Post-dubstep’s artistic peak; dismantles the genre’s aggression entirely, leaving only raw emotional space.", time: "45:00" }
    ]
  },
  {
    freq: 100.4,
    epNum: "06",
    genre: "BASSLINE",
    title: "EP 06 – BASSLINE & NICHE: UP THE M1 MOTORWAY",
    subtitle: "UP THE M1 MOTORWAY",
    desc: "Head north as Yorkshire and the Midlands flip garage into a faster, louder club rebellion. Sweet R&B vocals collide with sharp 4x4 rhythms and wild mid-range bass pressure. Tune the system and stay locked to the rhythm of the North.",
    duration1: "45:30",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ SHEFFIELD",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    colors: {
      neonPink: "#FF2DAA",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0e0a0d",
      surfaceLow: "#1c181b"
    },
    vinylImg: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Baseline magazine.png",
    cardDate: "08.01.26",
    cardEp: "EP 06 / NORTH",
    tracks1: [
      { title: "Agent X – Decoy (2003)", note: "The skeleton key; unleashes a sharp, mid-range squelch bassline that defines Sheffield’s raw underground sound.", time: "00:00" },
      { title: "Booda ft. Richard O – Niche Anthem (2003)", note: "The definitive declaration; names the club, names the sound, names a generation of northern ravers.", time: "03:45" },
      { title: "TRC – Oo Aa Ee (2005)", note: "Maximal northern energy; sweet female vocals collide with a distorted, mid-heavy bassline for pure dancefloor carnage.", time: "07:30" },
      { title: "Delinquent ft. Kcat – My Destiny (2006)", note: "The emotional peak of the genre; a bittersweet R&B vocal elevated by heavyweight Yorkshire bass pressure.", time: "11:15" },
      { title: "TS7 – Bradford (2007)", note: "The Bradford anthem; raw, unfiltered regional pride delivered over a relentlessly bouncing 4x4 rhythm.", time: "15:00" },
      { title: "DJ Q – The Original (2004)", note: "The title says it all; DJ Q crystallises the original, purist bassline house sound with expert precision.", time: "18:45" },
      { title: "T2 ft. Jodie – Heartbroken (2007)", note: "Crossover gold; an irresistible, emotionally direct anthem that carried bassline into the national mainstream.", time: "22:30" },
      { title: "H “Two” O ft. Platnum – What’s It Gonna Be (2008)", note: "The chart breakthrough that proved bassline’s pop potential, despite the underground’s fierce resistance.", time: "26:15" },
      { title: "DJ Q ft. MC Bonez – You Wot! (2007)", note: "The ultimate MC-led bassline anthem; raw energy and unmistakable northern accent define a scene’s voice.", time: "30:00" },
      { title: "Danny Bond – The Pipe (2008)", note: "Pure, mechanical aggression; a monster sub-bass workout built for maximum system pressure and dancefloor dominance.", time: "33:45" },
      { title: "Wideboys – Sambuca (Bassline Mix) (2008)", note: "The London connection; West London producers make an unlikely, successful pilgrimage up the M1 motorway.", time: "37:30" },
      { title: "Crazy Cousinz – Bongo Jam (2008)", note: "A crucial transitional record that connects bassline’s northern energy directly to London’s emerging UK Funky movement.", time: "41:15" }
    ]
  },
  {
    freq: 102.7,
    epNum: "07",
    genre: "UK FUNKY",
    title: "EP 07 – UK FUNKY: THE TRIBAL SHIFT",
    subtitle: "SOCA PERCUSSION & EUPHORIC VOCALS",
    desc: "Feel warmth return to the underground as London swaps darkness for movement and celebration. Soulful house blends with syncopated African percussion to create a fresh new bounce. Lock in the dial and keep the sound system tuned to the evolution.",
    duration1: "50:11",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ STRATFORD, EAST LONDON",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    colors: {
      neonPink: "#FF6B1A",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0a0e0a",
      surfaceLow: "#181c18"
    },
    vinylImg: "https://images.unsplash.com/photo-1487180142328-054b783fc471?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Funky house magazine.png",
    cardDate: "19.01.26",
    cardEp: "EP 07 / TRIBAL",
    tracks1: [
      { title: "Fish Go Deep – The Cure & The Cause (Dennis Ferrer Remix) (2006)", note: "The deep house foundation stone; African percussion and soulful chords establish the genre’s warm blueprint.", time: "00:00" },
      { title: "Apple – Mr Choc (2007)", note: "An early UK Funky cornerstone; percussive, driving and deceptively sparse.", time: "03:30" },
      { title: "Crazy Cousinz – Bongo Jam (2008)", note: "The crucial bridge; transitions bassline’s northern energy directly into London’s emerging tribal house scene.", time: "07:00" },
      { title: "Princess Nyah – Frontline (Ill Blu Remix) (2008)", note: "Euphoric female vocals over complex tribal rhythms; the perfect encapsulation of UK Funky’s celebratory spirit.", time: "10:30" },
      { title: "Lil Silva – Seasons (2008)", note: "A deeply atmospheric, melancholic counterpoint; proves the genre can carry complex emotional weight.", time: "14:00" },
      { title: "Roska – Squark (2009)", note: "Raw percussive energy at its finest; Roska’s production is stripped back, organic and physically irresistible.", time: "17:30" },
      { title: "Marcus Nasty & Macabre Unit – Funky Monkey (2009)", note: "The pirate radio anthem; raw, unapologetic and perfectly calibrated for illegal Rinse FM transmission.", time: "21:00" },
      { title: "Donae’o – Party Hard (2009)", note: "The crossover moment; UK Funky’s irresistible rhythmic bounce breaks out of the underground and into clubs nationwide.", time: "24:30" },
      { title: "Egypt – In The Morning (2009)", note: "Sophisticated soulful vocals over a complex, multi-layered percussion groove that rewards repeated listens.", time: "28:00" },
      { title: "Gracious K – Migraine Skank (2009)", note: "A ridiculous, joyful viral phenomenon; the migraine skank dance move transcends the underground entirely.", time: "31:30" },
      { title: "K.I.G – Head, Shoulders, Kneez & Toez (2009)", note: "Novelty song to national phenomenon; an irresistible earworm that introduced UK Funky to the mainstream.", time: "35:00" },
      { title: "DJ Zinc ft. Ms. Dynamite – Wile Out (2010)", note: "A veteran legend reinventing himself; connects the jungle’s DNA to UK Funky’s tribal rhythms seamlessly.", time: "38:30" },
      { title: "Sneakbo – Touch Ah Button (2011)", note: "A transitional landmark; UK Funky’s tribal bass begins dissolving into the afro-influenced sound of Afroswing.", time: "42:00" },
      { title: "D’banj – Oliver Twist (2012)", note: "Global Afrobeats crossover complete; Nigerian pop fully colonises the UK charts and signals the genre’s endpoint.", time: "45:30" }
    ]
  },
  {
    freq: 105.0,
    epNum: "08",
    genre: "ROAD RAP",
    title: "EP 08 – UK ROAD RAP: TALKIN’ THE HARDEST",
    subtitle: "SOUTH LONDON STREET STORIES",
    desc: "Step into 2007 as a new wave of street storytellers slows the tempo and speaks with brutal clarity. DVD culture, mixtapes, and heavy 808s shape a raw new voice from the estates. Dial in and stay locked to the underground pulse.",
    duration1: "48:12",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ BRIXTON",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    colors: {
      neonPink: "#2f2e2e",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0d0a0a",
      surfaceLow: "#1a1515"
    },
    vinylImg: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Road Rap magazine.png",
    cardDate: "02.02.26",
    cardEp: "EP 08 / ROAD",
    tracks1: [
      { title: "Giggs – Talkin the Hardest (2007)", note: "The founding document; Giggs’s deep, unhurried delivery and vivid street storytelling launch a whole new genre.", time: "00:00" },
      { title: "PDC – Villain (2008)", note: "Raw collective power from Peckham’s finest; uncompromising street narratives over heavyweight 808 production.", time: "03:40" },
      { title: "K Koke – Are You Listening (2010)", note: "Lyrical precision over dark, cinematic beats; K Koke establishes himself as road rap’s most gifted wordsmith.", time: "07:20" },
      { title: "Blade Brown – Bags and Boxes (2010)", note: "Effortlessly cool delivery over a hazy, atmospheric beat; Blade Brown’s most iconic and influential record.", time: "11:00" },
      { title: "Youngs Teflon – Nandos (2010)", note: "Vivid, hyperlocal London street detail and sharp wit; a future road rap classic that defined an era.", time: "14:40" },
      { title: "Sneakbo – The Wave (2011)", note: "The South London sound fully formed; Sneakbo’s melodic flow bridges road rap to the incoming Afroswing movement.", time: "18:20" },
      { title: "Nines – From Church Road to Hollywood (2011)", note: "Biographical mastery; Nines translates complex personal hardship into compelling, cinematic street narrative.", time: "22:00" },
      { title: "Potter Payper – Training Day (2013)", note: "A bruising, unfiltered masterclass; lyrical density and personal authenticity at the absolute peak of road rap.", time: "25:40" },
      { title: "Casisdead – Drugs Don’t Work (2013)", note: "Deadpan darkness elevated to art; an anonymous, masked figure reframes the entire genre with black humour.", time: "29:20" },
      { title: "Krept & Konan – Don’t Waste My Time (2013)", note: "Duo chemistry perfectly showcased; two very different flows create an irresistible and deeply personal narrative.", time: "33:00" },
      { title: "Skrapz – Los Pollos Hermanos (2014)", note: "Pop culture lyricism meets raw street reality; Skrapz’s clever cultural references elevate road rap’s artistic range.", time: "36:40" },
      { title: "Section Boyz – Lock Arff (2015)", note: "A wave-defining collective anthem; Section Boyz fuse road rap’s weight with a melodic, drillish energy that previews the future.", time: "40:20" },
      { title: "67 – Let’s Lurk (2016)", note: "Ruthless, energetic menace over sinister production; a transitional record bridging road rap and the incoming UK drill sound.", time: "44:00" }
    ]
  },
  {
    freq: 107.3,
    epNum: "09",
    genre: "UK DRILL",
    title: "EP 09 – UK DRILL: BRIXTON BLUEPRINT",
    subtitle: "SLIDING BASS & BRUTALIST NARRATIVES",
    desc: "Witness the rise of Britain’s most controversial and globally influential street sound. Chicago drill is rebuilt in South London with sliding basslines, sharp snares, and rapid-fire hats. Tune the system and hold the frequency of the streets.",
    duration1: "44:50",
    bitrate: "320 KBPS",
    location: "BLACK BUDDHA HQ KENNINGTON",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
    colors: {
      neonPink: "#FF2A2A",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0a070e",
      surfaceLow: "#15101c"
    },
    vinylImg: "https://images.unsplash.com/photo-1571330735066-03add572b786?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Drill Magazine.png",
    cardDate: "16.02.26",
    cardEp: "EP 09 / BRIXTON",
    tracks1: [
      { title: "150 – Look How I’m Smiling (2014)", note: "The zero-hour record; raw, unyielding violence as testimony, establishing the UK’s own drill grammar.", time: "00:00" },
      { title: "67 – Let’s Lurk (2016)", note: "Cold-blooded energy over sinister sliding basslines; the record that fully defines the South London drill aesthetic.", time: "03:10" },
      { title: "Harlem Spartans – Kennington Where It Started (2017)", note: "Hyperlocal pride anthem; the Spartans’ vivid, visceral geography puts Kennington on the global map.", time: "06:20" },
      { title: "Zone 2 – Zone 2 Step (2017)", note: "Collective aggression weaponized; Tottenham’s Zone 2 bring North London energy to a genre previously dominated by the South.", time: "09:30" },
      { title: "Loski – Hazards (2017)", note: "Effortless flow over atmospheric production; Loski’s technical mastery and streetwise intelligence set him apart immediately.", time: "12:40" },
      { title: "Headie One x RV – Know Better (2018)", note: "Two contrasting voices in perfect dialogue; the record that signalled Headie One’s evolution into a genuine superstar.", time: "15:50" },
      { title: "Unknown T – Homerton B (2018)", note: "East London’s definitive declaration; raw, hyperlocal pride and unrelenting energy from Hackney’s finest.", time: "19:00" },
      { title: "Russ Millions x Tion Wayne – Keisha & Becky (2019)", note: "Playful, commercial drill perfected; flips the genre’s aggression into irresistible pop-culture hooks.", time: "22:10" },
      { title: "Headie One – 18HUNNA (2019)", note: "Drill goes luxury; Headie bridges gritty street reality with high-end aesthetics, cementing his crossover status.", time: "25:20" },
      { title: "Central Cee – Day in the Life (2020)", note: "The independent takeover; Central Cee strips away block affiliations for sleek, universal street observations.", time: "28:30" },
      { title: "Central Cee – Loading (2020)", note: "Commercial drill masterclass; nostalgic jazz horns meet rolling 808s, expanding the genre’s global demographic.", time: "31:40" },
      { title: "Tion Wayne x Russ Millions – Body (2021)", note: "The historic apex; the first pure UK drill record to capture the Official Singles Number 1 spot.", time: "34:50" },
      { title: "SR – Welcome To Brixton (2020)", note: "A menacing warning siren and dark underground textures hijack the international digital algorithm.", time: "38:00" },
      { title: "Dave & Central Cee – Sprinter (2023)", note: "Elite UK star power combines a lightweight drill bounce with luxury acoustic guitar loops for a 10-week Number 1 run.", time: "41:10" }
    ]
  },
  {
    freq: 109.8,
    epNum: "10",
    genre: "AFROSWING",
    title: "EP 10 – AFROSWING: TRANSATLANTIC ROYALTY",
    subtitle: "MELODIC DANCEHALL & AFROBEATS FUSION",
    desc: "Step out of the darkness as Afroswing brings melody, rhythm, and celebration to the forefront. British bass culture merges with West African highlife and Jamaican dancehall into something vibrant and global. Lock in the dial and stay tuned to the sound system.",
    duration1: "53:40",
    bitrate: "320 KBPS",
    location: "EAST LONDON TRANSIT DOCK",
    trackUrl1: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3",
    colors: {
      neonPink: "#00C2B2",
      neonGreen: "#a1fb00",
      surfaceLowest: "#0e090b",
      surfaceLow: "#1c1216"
    },
    vinylImg: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=80&w=400&auto=format&fit=crop",
    cardImg: "images/Afro swing Magazine.png",
    cardDate: "02.03.26",
    cardEp: "EP 10 / ROYAL",
    tracks1: [
      { title: "J Hus – Did You See (2017)", note: "The undisputed blueprint. J Hus and Jae5 balance London rap cadences with undeniable African melodies, shifting British pop history.", time: "00:00" },
      { title: "Kojo Funds x J Hus – Warning (2016)", note: "Underground clash of titans; crystallizes the genre’s title with a rugged, dancehall-infused vocal style carrying immense street weight.", time: "03:50" },
      { title: "Not3s – Addison Lee (2017)", note: "Digital virality unlocked; trades complex lyricism for an inescapable, lighthearted hook that defined London’s youth culture.", time: "07:40" },
      { title: "Dave ft. J Hus – Samantha (2017)", note: "Elite lyricism meets melodic diaspora waves. Dave’s introspective piano storytelling provides a stark contrast to Hus’s infectious chorus.", time: "11:30" },
      { title: "IAMDDB – Shade (2017)", note: "Manchester’s female vanguard injects hazy trap and neo-soul into the rhythmic bounce, creating a smoked-out club staple.", time: "15:20" },
      { title: "Ramz – Barking (2017)", note: "Total chart saturation; an upbeat, universally relatable anthem peaks at Number 2, establishing Afroswing as the national soundtrack.", time: "19:10" },
      { title: "Krept & Konan – Freak of the Week (2015)", note: "Early foundational crossover template; high-end R&B trends collide with a massive, platinum-selling club bounce.", time: "23:00" },
      { title: "MoStack – Shine Girl (2019)", note: "The superstar link-up; MoStack utilizes his signature cheeky, melodic flow alongside Stormzy to craft an empowering summer staple.", time: "26:50" },
      { title: "D-Block Europe – Kitchen Kings (2019)", note: "The evolution into the ‘Wave’; Young Adz and Dirtbike LB fuse Atlanta’s autotuned trap aesthetics with raw UK slang.", time: "30:40" },
      { title: "Aitch – Taste (Make It Shake) (2019)", note: "The melodic swing travels North; Manchester’s Aitch delivers a highly charismatic, bouncy flow over a stripped-back bass-heavy riddim.", time: "34:30" },
      { title: "Dave ft. Burna Boy – Location (2019)", note: "Cross-continental bridge; a flawless, multi-platinum anthem linking elite UK rap directly with the global Afrobeats explosion.", time: "38:20" },
      { title: "Stormzy ft. Ed Sheeran & Burna Boy – Own It (2019)", note: "A historic Number 1 hit uniting UK rap weight, global pop royalty, and African giants on one dancefloor.", time: "42:10" },
      { title: "J Hus ft. Drake – Who Told You (2023)", note: "Reclaiming the Afroswing crown; an effortlessly smooth summer hit backed by a massive transatlantic co-sign from Toronto.", time: "46:00" },
      { title: "NSG – Grandad (2020)", note: "The East London collective perfects the communal, laid-back afro-fusion vibe for the 2020s scene.", time: "49:50" }
    ]
  }
];

if (typeof module !== 'undefined') { module.exports = STATIONS; }
